/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.red.interfazUI;

import com.example.red.controlador.Coordinador;
import java.util.List;

import com.example.red.interfaz.Interfaz;
import com.example.red.modelo.Conexion;
import com.example.red.modelo.Equipo;
import com.example.red.modelo.Ubicacion;
import com.example.red.negocio.Calculo;
import com.example.red.negocio.Red;
import java.util.Map;
/**
 *
 * @author Lautaro
 */
public class interfazUI extends javax.swing.JFrame {
    private Red red;
    private Calculo calculo;

    // vista
    private Interfaz interfaz;
    // controlador
    private Coordinador coordinador;
    /**
     * Creates new form interfazUI
     */
    public interfazUI() {
        initComponents();
        red = Red.getRed();
        calculo = new Calculo();
        coordinador = new Coordinador();
        interfaz = new Interfaz();

        calculo.setCoordinador(coordinador);
        interfaz.setCoordinador(coordinador);

        coordinador.setCalculo(calculo);
        coordinador.setInterfaz(interfaz);
        coordinador.setRed(red);
        
        
    }
    private void consultar() {
        calculo.cargarDatos(red.getTablaEquipos(), red.getConexiones());
        interfaz.cargarDatos(red.getTablaEquipos(), red.getTablaConexiones());

        interfaz.iniciarConsola();
        interfaz.iniciarInterfaz();
        interfaz.mostrarMenu();
     
        interfaz.cerrarConsola();
        interfaz.cerrarInterfaz();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PingPanel = new javax.swing.JPanel();
        PingBox = new javax.swing.JComboBox<>();
        PingBoton = new javax.swing.JButton();
        TracePanel = new javax.swing.JPanel();
        TraceBox1 = new javax.swing.JComboBox<>();
        TraceBox2 = new javax.swing.JComboBox<>();
        TraceBoton = new javax.swing.JButton();
        RangoPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        RangoBoton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 133, 132));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PingPanel.setBackground(new java.awt.Color(233, 233, 233));

        PingBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AP01", "Item 2", "Item 3", "Item 4" }));
        PingBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PingBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PingBoxMouseExited(evt);
            }
        });
        PingBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PingBoxActionPerformed(evt);
            }
        });

        PingBoton.setText("Realizar Ping");
        PingBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PingBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PingBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PingBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PingPanelLayout = new javax.swing.GroupLayout(PingPanel);
        PingPanel.setLayout(PingPanelLayout);
        PingPanelLayout.setHorizontalGroup(
            PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PingPanelLayout.createSequentialGroup()
                .addGroup(PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PingPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(PingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PingPanelLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(PingBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        PingPanelLayout.setVerticalGroup(
            PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PingPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(PingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(PingBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Ping", PingPanel);

        TracePanel.setBackground(new java.awt.Color(233, 233, 233));

        TraceBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AP01", "Item 2", "Item 3", "Item 4" }));
        TraceBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBox1MouseExited(evt);
            }
        });

        TraceBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AP03", "Item 2", "Item 3", "Item 4" }));
        TraceBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBox2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBox2MouseExited(evt);
            }
        });

        TraceBoton.setText("Trazar Ruta");
        TraceBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraceBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBotonMouseExited(evt);
            }
        });
        TraceBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraceBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TracePanelLayout = new javax.swing.GroupLayout(TracePanel);
        TracePanel.setLayout(TracePanelLayout);
        TracePanelLayout.setHorizontalGroup(
            TracePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TracePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(TraceBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(TraceBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(TracePanelLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(TraceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TracePanelLayout.setVerticalGroup(
            TracePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TracePanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(TracePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TraceBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(TraceBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(TraceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Traceroute", TracePanel);

        RangoPanel.setBackground(new java.awt.Color(233, 233, 233));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RangoBoton.setText("jButton1");
        RangoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RangoBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RangoPanelLayout = new javax.swing.GroupLayout(RangoPanel);
        RangoPanel.setLayout(RangoPanelLayout);
        RangoPanelLayout.setHorizontalGroup(
            RangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RangoPanelLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addGroup(RangoPanelLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(RangoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RangoPanelLayout.setVerticalGroup(
            RangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RangoPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(RangoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Rango", RangoPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 260));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 580, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TraceBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraceBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraceBotonActionPerformed

    private void PingBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PingBotonMouseEntered
        PingBoton.setBackground(new java.awt.Color(0, 133, 132));
    }//GEN-LAST:event_PingBotonMouseEntered

    private void PingBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PingBotonMouseExited
        PingBoton.setBackground(new java.awt.Color(225, 225, 225));
    }//GEN-LAST:event_PingBotonMouseExited

    private void TraceBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraceBotonMouseEntered
        TraceBoton.setBackground(new java.awt.Color(0, 133, 132));
    }//GEN-LAST:event_TraceBotonMouseEntered

    private void TraceBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraceBotonMouseExited
        TraceBoton.setBackground(new java.awt.Color(225, 225, 225));
    }//GEN-LAST:event_TraceBotonMouseExited

    private void PingBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PingBotonMouseClicked
        String id = red.validarEquipo((String)PingBox.getSelectedItem());
        if (id != null){
            jLabel1.setText("Equipo '" + id + "' " + (calculo.ping(id) ? "activo" : "inactivo"));         
        } else {
            jLabel1.setText("El equipo '" + (String)PingBox.getSelectedItem()+"' no se ha encontrado en la red");
        }       
        
    }//GEN-LAST:event_PingBotonMouseClicked

    private void PingBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PingBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PingBoxActionPerformed

    private void TraceBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraceBotonMouseClicked
        String id1 = red.validarEquipo((String)TraceBox1.getSelectedItem());
        String id2 = red.validarEquipo((String)TraceBox2.getSelectedItem());
        List<String> resultado = null;
        if (id1 != null && id2 != null)
            resultado = calculo.traceRoute(id1, id2);
        if (resultado == null)
            jLabel1.setText("Al menos un equipo no se ha encontrado en la red");
        else if (resultado.isEmpty())
            jLabel1.setText("No se ha encontrado un camino de equipos activos");
        else if (!resultado.get(0).equals(id1) || !resultado.get(resultado.size() - 1).equals(id2))
            jLabel1.setText("No se ha encontrado un camino de equipos activos");
        else {
            jLabel1.setText("Camino encontrado:");
            for (int i = 0; i < resultado.size() - 1; i++) {
                id1 = resultado.get(i);
                id2 = resultado.get(i + 1);
                jLabel1.setText("- " + id1 + " -> " + id2);
            }                       
        }
    }//GEN-LAST:event_TraceBotonMouseClicked

    private void PingBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PingBoxMouseEntered
        PingBox.setBackground(new java.awt.Color(0, 133, 132));
    }//GEN-LAST:event_PingBoxMouseEntered

    private void PingBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PingBoxMouseExited
        PingBox.setBackground(new java.awt.Color(225, 225, 225));
    }//GEN-LAST:event_PingBoxMouseExited

    private void RangoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RangoBotonMouseClicked
        List<String> equiposConEsaIP = red.rangoEquiposIP((String)jComboBox1.getSelectedItem());
        if (equiposConEsaIP.isEmpty())
            jLabel1.setText("Ningun equipo encontrado");
        else {
            Map<String, Boolean> resultado = calculo.rangoPing(equiposConEsaIP);
            jLabel1.setText("Estado de los equipos: \n");
            for (Map.Entry<String, Boolean> entry : resultado.entrySet()) {
                String id = entry.getKey();
                boolean isActivo = entry.getValue();
                jLabel1.setText(id + " " + (isActivo ? "activo" : "inactivo"));               
            }
        }
    }//GEN-LAST:event_RangoBotonMouseClicked

    private void TraceBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraceBox1MouseEntered
        TraceBox1.setBackground(new java.awt.Color(0, 133, 132));
    }//GEN-LAST:event_TraceBox1MouseEntered

    private void TraceBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraceBox1MouseExited
        TraceBox1.setBackground(new java.awt.Color(225, 225, 225));
    }//GEN-LAST:event_TraceBox1MouseExited

    private void TraceBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraceBox2MouseEntered
        TraceBox2.setBackground(new java.awt.Color(0, 133, 132));
    }//GEN-LAST:event_TraceBox2MouseEntered

    private void TraceBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraceBox2MouseExited
        TraceBox2.setBackground(new java.awt.Color(225, 225, 225));
    }//GEN-LAST:event_TraceBox2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PingBoton;
    private javax.swing.JComboBox<String> PingBox;
    private javax.swing.JPanel PingPanel;
    private javax.swing.JButton RangoBoton;
    private javax.swing.JPanel RangoPanel;
    private javax.swing.JButton TraceBoton;
    private javax.swing.JComboBox<String> TraceBox1;
    private javax.swing.JComboBox<String> TraceBox2;
    private javax.swing.JPanel TracePanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
