/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.red.interfaz_ui;

import com.example.red.controladorUI.CoordinadorUI;

import java.util.HashMap;
import java.util.List;

import com.example.red.interfaz.Interfaz;
import com.example.red.controladorUI.AplicacionUI;
import com.example.red.modelo.Conexion;
import com.example.red.modelo.Equipo;

import com.example.red.negocio.Calculo;
import com.example.red.negocio.Red;
import java.util.Map;

/**
 *
 * @author Lautaro
 */
public class InterfazUI extends javax.swing.JFrame {
    private Red red;
    private Calculo calculo;

    /**
     * Creates new form interfazUI
     */
    public InterfazUI() {
        initComponents();
        red = Red.getRed();
        calculo = new Calculo();
        calculo.cargarDatos(red.getTablaEquipos(), red.getConexiones());

        RangoBox1.addItem("192.168.16");
        PingBoton.setBackground(new java.awt.Color(225, 225, 225));
        TraceBoton.setBackground(new java.awt.Color(225, 225, 225));
        RangoBoton.setBackground(new java.awt.Color(225, 225, 225));

        for (Equipo equipo : red.getEquipos()) {
            String displayText = equipo.getCodigo();

            PingBox.addItem(displayText);
            TraceBox1.addItem(displayText);
            TraceBox2.addItem(displayText);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PingPanel = new javax.swing.JPanel();
        PingBox = new javax.swing.JComboBox<>();
        PingBoton = new javax.swing.JButton();
        TracePanel = new javax.swing.JPanel();
        TraceBox1 = new javax.swing.JComboBox<>();
        TraceBox2 = new javax.swing.JComboBox<>();
        TraceBoton = new javax.swing.JButton();
        DecorLabel = new javax.swing.JLabel();
        RangoPanel = new javax.swing.JPanel();
        RangoBox1 = new javax.swing.JComboBox<>();
        RangoBoton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 133, 132));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        PingPanel.setBackground(new java.awt.Color(233, 233, 233));

        PingBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PingBoxMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                PingBoxMouseExited(evt);
            }
        });
        PingBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PingBoxActionPerformed(evt);
            }
        });

        PingBoton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        PingBoton.setText("Realizar Ping");
        PingBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PingBotonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PingBotonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                PingBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PingPanelLayout = new javax.swing.GroupLayout(PingPanel);
        PingPanel.setLayout(PingPanelLayout);
        PingPanelLayout.setHorizontalGroup(
                PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PingPanelLayout.createSequentialGroup()
                                .addGroup(PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PingPanelLayout.createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(PingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PingPanelLayout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(PingBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(280, Short.MAX_VALUE)));
        PingPanelLayout.setVerticalGroup(
                PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PingPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(PingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61,
                                        Short.MAX_VALUE)
                                .addComponent(PingBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addGap(31, 31, 31)));

        jTabbedPane1.addTab("Ping", PingPanel);

        TracePanel.setBackground(new java.awt.Color(233, 233, 233));

        TraceBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBox1MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBox1MouseExited(evt);
            }
        });
        TraceBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraceBox1ActionPerformed(evt);
            }
        });

        TraceBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBox2MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBox2MouseExited(evt);
            }
        });

        TraceBoton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TraceBoton.setText("Trazar Ruta");
        TraceBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraceBotonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBotonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBotonMouseExited(evt);
            }
        });
        TraceBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraceBotonActionPerformed(evt);
            }
        });

        DecorLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DecorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DecorLabel.setText(" < - - - - - ? ? ? - - - - - >");

        javax.swing.GroupLayout TracePanelLayout = new javax.swing.GroupLayout(TracePanel);
        TracePanel.setLayout(TracePanelLayout);
        TracePanelLayout.setHorizontalGroup(
                TracePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TracePanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(TraceBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DecorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(TraceBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(102, Short.MAX_VALUE))
                        .addGroup(TracePanelLayout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(TraceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(280, Short.MAX_VALUE)));
        TracePanelLayout.setVerticalGroup(
                TracePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TracePanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(TracePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TraceBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 50,
                                                Short.MAX_VALUE)
                                        .addComponent(TraceBox1)
                                        .addComponent(DecorLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28,
                                        Short.MAX_VALUE)
                                .addComponent(TraceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)));

        jTabbedPane1.addTab("Traceroute", TracePanel);

        RangoPanel.setBackground(new java.awt.Color(233, 233, 233));

        RangoBox1.setEditable(true);
        RangoBox1.setSelectedIndex(-1);
        RangoBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RangoBox1MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                RangoBox1MouseExited(evt);
            }
        });

        RangoBoton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        RangoBoton.setText("Ver equipos");
        RangoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RangoBotonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RangoBotonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                RangoBotonMouseExited(evt);
            }
        });
        RangoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RangoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RangoPanelLayout = new javax.swing.GroupLayout(RangoPanel);
        RangoPanel.setLayout(RangoPanelLayout);
        RangoPanelLayout.setHorizontalGroup(
                RangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RangoPanelLayout.createSequentialGroup()
                                .addContainerGap(237, Short.MAX_VALUE)
                                .addComponent(RangoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(253, 253, 253))
                        .addGroup(RangoPanelLayout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(RangoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        RangoPanelLayout.setVerticalGroup(
                RangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RangoPanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(RangoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33,
                                        Short.MAX_VALUE)
                                .addComponent(RangoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)));

        jTabbedPane1.addTab("Rango", RangoPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 640, 260));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 628, 80));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 630, 21));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 640, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PingBotonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBotonMouseEntered
        PingBoton.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_PingBotonMouseEntered

    private void PingBotonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBotonMouseExited
        PingBoton.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_PingBotonMouseExited

    private void TraceBotonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBotonMouseEntered
        TraceBoton.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_TraceBotonMouseEntered

    private void TraceBotonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBotonMouseExited
        TraceBoton.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_TraceBotonMouseExited

    private void PingBotonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBotonMouseClicked
        String id = red.validarEquipo((String) PingBox.getSelectedItem());
        jLabel2.setText("");
        if (id != null) {
            jLabel1.setText("Equipo '" + id + "' " + (calculo.ping(id) ? "activo" : "inactivo"));
        } else {
            jLabel1.setText("El equipo '" + (String) PingBox.getSelectedItem() + "' no se ha encontrado en la red");
        }

    }// GEN-LAST:event_PingBotonMouseClicked

    private void PingBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PingBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PingBoxActionPerformed

    private void TraceBotonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBotonMouseClicked
        String id1 = (String) TraceBox1.getSelectedItem();
        String id2 = (String) TraceBox2.getSelectedItem();
        List<String> resultado = null;
        String msj = "";
        if (id1 != null && id2 != null)
            resultado = calculo.traceRoute(id1, id2);
        if (resultado == null) {
            jLabel1.setText("Al menos un equipo no se ha encontrado en la red");
            jLabel2.setText(":c");
        } else if (resultado.isEmpty()) {
            jLabel1.setText("No se ha encontrado un camino de equipos activos");
            jLabel2.setText(":c");
        }
        // else if (!resultado.get(0).equals(id1) || !resultado.get(resultado.size() -
        // 1).equals(id2)){ ESTE DA FALSO POSITIVO
        // jLabel1.setText("No se ha encontrado un camino de equipos activos");
        // jLabel2.setText(":c");}
        else {
            jLabel2.setText("Camino encontrado:");
            for (int i = 0; i < resultado.size() - 1; i++) {
                id1 = resultado.get(i);
                id2 = resultado.get(i + 1);
                msj = msj + ("- " + id1 + " -> " + id2);
            }
            jLabel1.setText(msj);
        }
    }// GEN-LAST:event_TraceBotonMouseClicked

    private void PingBoxMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBoxMouseEntered
        PingBox.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_PingBoxMouseEntered

    private void PingBoxMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBoxMouseExited
        PingBox.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_PingBoxMouseExited

    private void RangoBotonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBotonMouseClicked
        List<String> equiposConEsaIP = red.rangoEquiposIP((String) RangoBox1.getSelectedItem());
        String msj = "";
        if (equiposConEsaIP.isEmpty()) {
            jLabel1.setText("Ningun equipo encontrado");
            jLabel2.setText("F");
        } else {
            Map<String, Boolean> resultado = calculo.rangoPing(equiposConEsaIP);
            jLabel2.setText("Estado de los equipos:");
            for (Map.Entry<String, Boolean> entry : resultado.entrySet()) {
                String id = entry.getKey();
                boolean isActivo = entry.getValue();
                msj = msj + (id + " " + (isActivo ? "activo \n" : "inactivo \n"));

            }
            jLabel1.setText(msj);
        }
    }// GEN-LAST:event_RangoBotonMouseClicked

    private void TraceBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TraceBox1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox1MouseEntered
        TraceBox1.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_TraceBox1MouseEntered

    private void TraceBox1MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox1MouseExited
        TraceBox1.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_TraceBox1MouseExited

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void TraceBox2MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox2MouseEntered
        TraceBox2.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_TraceBox2MouseEntered

    private void TraceBox2MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox2MouseExited
        TraceBox2.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_TraceBox2MouseExited

    private void RangoBotonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RangoBotonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_RangoBotonActionPerformed

    private void RangoBotonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBotonMouseExited
        RangoBoton.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_RangoBotonMouseExited

    private void RangoBotonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBotonMouseEntered
        RangoBoton.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_RangoBotonMouseEntered

    private void RangoBox1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBox1MouseEntered
        RangoBox1.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_RangoBox1MouseEntered

    private void RangoBox1MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBox1MouseExited
        RangoBox1.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_RangoBox1MouseExited

    private void TraceBotonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DecorLabel;
    private javax.swing.JButton PingBoton;
    private javax.swing.JComboBox<String> PingBox;
    private javax.swing.JPanel PingPanel;
    private javax.swing.JButton RangoBoton;
    private javax.swing.JComboBox<String> RangoBox1;
    private javax.swing.JPanel RangoPanel;
    private javax.swing.JButton TraceBoton;
    private javax.swing.JComboBox<String> TraceBox1;
    private javax.swing.JComboBox<String> TraceBox2;
    private javax.swing.JPanel TracePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
