/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.red.gui;

import com.example.red.conexion.ConexionBD;
import com.example.red.modelo.Equipo;
import com.example.red.modelo.Conexion;
import com.example.red.modelo.TipoCable;
import com.example.red.modelo.TipoPuerto;
import com.example.red.negocio.Red;
import java.awt.Color;
import java.util.ResourceBundle;

import javax.swing.table.DefaultTableModel;
import com.example.red.servicio.ConexionServiceImpl;
import com.example.red.servicio.IdiomaService;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author Lautaro
 */
public class ConexionList extends javax.swing.JFrame {
    //private Red red; 
   
   private ConexionServiceImpl ConService = new ConexionServiceImpl();
    DefaultTableModel E = new DefaultTableModel();
    private ResourceBundle idioma;

    /**
     * Creates new form ConexionList
     */
    public ConexionList() {
        idioma = IdiomaService.getRb();
        initComponents();
        setTable();       
       // calculo = new Calculo();
        //calculo.cargarDatos(red.getTablaEquipos(), red.getConexiones());
       setDatos();
       // Configurar que la ventana no se pueda redimensionar
        this.setResizable(false);
        // Centrar la ventana en la pantalla
        this.setLocationRelativeTo(null);
    }
    
    private void setTable (){                     //CREA Y NOMBRA COLUMNAS    
    String[] title = {idioma.getString("label_equipo1"),idioma.getString("label_puerto1"),idioma.getString("label_equipo2"),idioma.getString("label_puerto2"), idioma.getString("label_cable")};
    E.setColumnIdentifiers(title);
    TableConex.setModel(E);
    }
    private void setDatos(){                      //CREA FILA PARA CADA Conexion
        Red ned = new Red();
        Object[] datos = new Object[E.getColumnCount()];
        for (Conexion hard : ned.getConexiones()) {
            Equipo E1 = hard.getEquipo1();
            Equipo E2 = hard.getEquipo2();
            TipoCable C = hard.getTipocable();
            TipoPuerto P1 = hard.getTipoPuerto1();
            TipoPuerto P2 = hard.getTipoPuerto2();
            datos[0] = E1.getCodigo();
            datos[1] = P1.getCodigo();
            datos[2] = E2.getCodigo();
            datos[3] = P2.getCodigo();
            datos[4] = C.getCodigo();
            E.addRow(datos);
        }
        
    }
     void ResetTabla(){
        E.setRowCount(0);      
        setDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableConex = new javax.swing.JTable();
        AddConex = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TableConex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableConex);

        AddConex.setBackground(new java.awt.Color(0, 133, 132));
        AddConex.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AddConex.setForeground(new java.awt.Color(255, 255, 255));
        AddConex.setText("Agregar");
        AddConex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddConexMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddConexMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddConexMouseExited(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 133, 132));
        jButton2.setText("Modificar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        BorrarBoton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BorrarBoton.setForeground(new java.awt.Color(0, 133, 132));
        BorrarBoton.setText("Borrar");
        BorrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BorrarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BorrarBotonMouseExited(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(0, 133, 132));
        jButton1.setText("Reset");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText(" ");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrador de Conexiones");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Toque los botones \"Modificar\" para cambiar caracteristicas");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("o \"Agregar\"  ingresar una nueva conexion.");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Si desea eliminar una conexion. seleccionelo de la lista, luego toque \"Borrar\".");

        jLabel9.setFont(new java.awt.Font("SansSerif", 3, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("¡Advertencia, esta accion no puede desaserse!");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Al terminar cada accion toque \"Reset\" para ver los cambios reflejados");
        jLabel10.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(AddConex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(73, 73, 73)
                        .addComponent(BorrarBoton)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BorrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddConex, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddConexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddConexMouseClicked
        ConexionAdd.main(null);
    }//GEN-LAST:event_AddConexMouseClicked

    private void AddConexMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddConexMouseEntered
        AddConex.setBackground(new java.awt.Color(100,204,79));
    }//GEN-LAST:event_AddConexMouseEntered

    private void AddConexMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddConexMouseExited
        AddConex.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_AddConexMouseExited

    private void BorrarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarBotonMouseEntered
        BorrarBoton.setBackground(Color.red);
    }//GEN-LAST:event_BorrarBotonMouseEntered

    private void BorrarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarBotonMouseExited
        BorrarBoton.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_BorrarBotonMouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     
        ConexionMod.main(null);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                          
        //red = Red.getRed();       
        ResetTabla();
    }                                     

    private void BorrarBotonMouseClicked(java.awt.event.MouseEvent evt) {
        Red ned = new Red();
    int selectRow = TableConex.getSelectedRow();
    if (selectRow != -1) {
        Equipo E1 = null, E2 = null;
        TipoPuerto P1 = null, P2 = null;
        TipoCable C1 = null;
        String AE1 = (String)TableConex.getValueAt(selectRow, 0);
        String AP1 = (String)TableConex.getValueAt(selectRow, 1);
        String AE2 = (String)TableConex.getValueAt(selectRow,2);
        String AP2 = (String)TableConex.getValueAt(selectRow, 3);
        String AC1 = (String)TableConex.getValueAt(selectRow, 4);
            // Obtener el número de columnas
            for (Equipo equipo : ned.getEquipos()) {
                String equi = equipo.getCodigo();
                if(equi.equals(AE1)){
                E1 = equipo;
                System.out.printf(E1.getCodigo());
                }
                if(equi.equals(AE2)){
                E2 = equipo;
                System.out.printf(E2.getCodigo());
                }                              
            }
            for (TipoPuerto puertos : ned.getTipoPuerto()){
                String pu = puertos.getCodigo();
                if(pu.equals(AP1)){
                P1 = puertos;
                System.out.printf(P1.getCodigo());
                }
                if(pu.equals(AP2)){
                P2 = puertos;
                System.out.printf(P2.getCodigo());
                }
            }
             for (TipoCable cables : ned.getTipoCable()){          
                String ca = cables.getCodigo();
                if(ca.equals(AC1)){
                C1 = cables;
                System.out.printf(C1.getCodigo());
                }}
        ConService.borrar(new Conexion(E1,E2,C1,P1,P2));
        jLabel1.setText(idioma.getString("label_conexion")+" "+ AE1 + ", " + AP1 + ", " + AE2 +", " + AP2 +", " + AC1 +" "+idioma.getString("label_borrado"));
    }}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        try {
            ConexionBD.getInstance().connectToDatabase();
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddConex;
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JTable TableConex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
