/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.red.gui;
import java.util.List;
import java.util.Map;

import com.example.red.conexion.ConexionBD;
import com.example.red.modelo.Equipo;
import com.example.red.negocio.Calculo;
import com.example.red.negocio.Red;
import java.awt.Color;


import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lautaro
 */
public class EquipoList extends javax.swing.JFrame {
    private Red red;
   // private Calculo calculo;
    private Equipo equipo;
    DefaultTableModel E = new DefaultTableModel();

    /**
     * Creates new form EquipoList
     */
    public EquipoList() {
        initComponents();
        setTable();
        red = Red.getRed();
       // calculo = new Calculo();
       // calculo.cargarDatos(red.getTablaEquipos(), red.getConexiones());
       setDatos();	
    }
    
    private void setTable (){                     //CREA Y NOMBRA COLUMNAS
    String[] title = {"Codigo","Nombre", "IP"};
    E.setColumnIdentifiers(title);
    TableEquipos.setModel(E);
    }
    private void setDatos(){                      //CREA FILA PARA CADA EQUIPO
        Object[] datos = new Object[E.getColumnCount()];
        for (Equipo hard : red.getEquipos()) {
            String codigo = hard.getCodigo();
            String nombre = hard.getDescripcion();
            datos[0] = codigo;
            datos[1] = nombre;
            datos[2] = hard.getDireccionesIP();
            E.addRow(datos);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEquipos = new javax.swing.JTable();
        AddBoton = new javax.swing.JButton();
        ModBoton = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TableEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableEquipos);

        AddBoton.setBackground(new java.awt.Color(0, 102, 102));
        AddBoton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AddBoton.setForeground(new java.awt.Color(255, 255, 255));
        AddBoton.setText("Agregar");
        AddBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddBotonMouseExited(evt);
            }
        });
        AddBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBotonActionPerformed(evt);
            }
        });

        ModBoton.setBackground(new java.awt.Color(0, 102, 102));
        ModBoton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ModBoton.setForeground(new java.awt.Color(255, 255, 255));
        ModBoton.setText("Modificar");

        BorrarBoton.setBackground(new java.awt.Color(0, 102, 102));
        BorrarBoton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BorrarBoton.setForeground(new java.awt.Color(255, 255, 255));
        BorrarBoton.setText("Borrar");
        BorrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BorrarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BorrarBotonMouseExited(evt);
            }
        });
        BorrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddBoton)
                        .addGap(50, 50, 50)
                        .addComponent(ModBoton)
                        .addGap(50, 50, 50)
                        .addComponent(BorrarBoton)
                        .addGap(100, 100, 100)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBoton)
                    .addComponent(ModBoton)
                    .addComponent(BorrarBoton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBotonActionPerformed

    private void BorrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarBotonActionPerformed

    private void BorrarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarBotonMouseExited
        BorrarBoton.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_BorrarBotonMouseExited

    private void BorrarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarBotonMouseEntered
        BorrarBoton.setBackground(Color.red);
    }//GEN-LAST:event_BorrarBotonMouseEntered

    private void AddBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBotonMouseEntered
        AddBoton.setBackground(new java.awt.Color(100,204,79));
    }//GEN-LAST:event_AddBotonMouseEntered

    private void AddBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBotonMouseExited
        AddBoton.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_AddBotonMouseExited

    private void AddBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBotonMouseClicked
        EquipoAdd.main(null);
    }//GEN-LAST:event_AddBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquipoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquipoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquipoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquipoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //Conexion a la base de datos
        try {
            ConexionBD.getInstance().connectToDatabase();
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquipoList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBoton;
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JButton ModBoton;
    private javax.swing.JTable TableEquipos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
