/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.red.gui;

import java.util.List;
import java.util.Map;

import com.example.red.conexion.ConexionBD;
import com.example.red.modelo.Equipo;
import com.example.red.negocio.Calculo;
import com.example.red.negocio.Red;
import com.example.red.gui.EquipoList;

/**
 *
 * @author Lautaro
 */
public class InterfazUI extends javax.swing.JFrame {
    private Red red;
    private Calculo calculo;

    /**
     * Creates new form interfazUI
     */
    public InterfazUI() {
        initComponents();
        red = Red.getRed();
        calculo = new Calculo();
        calculo.cargarDatos(red.getTablaEquipos(), red.getConexiones());

        RangoBox1.addItem("192.168.16");
        PingBoton.setBackground(new java.awt.Color(0, 102, 102));
        TraceBoton.setBackground(new java.awt.Color(0, 102, 102));
        RangoBoton.setBackground(new java.awt.Color(0, 102, 102));

        for (Equipo equipo : red.getEquipos()) {
            String displayText = equipo.getCodigo();

            PingBox.addItem(displayText);
            TraceBox1.addItem(displayText);
            TraceBox2.addItem(displayText);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        HelperLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PingPanel = new javax.swing.JPanel();
        PingBox = new javax.swing.JComboBox<>();
        PingBoton = new javax.swing.JButton();
        TracePanel = new javax.swing.JPanel();
        TraceBox1 = new javax.swing.JComboBox<>();
        TraceBox2 = new javax.swing.JComboBox<>();
        TraceBoton = new javax.swing.JButton();
        DecorLabel = new javax.swing.JLabel();
        RangoPanel = new javax.swing.JPanel();
        RangoBox1 = new javax.swing.JComboBox<>();
        RangoBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HelperLabel.setBackground(new java.awt.Color(0, 102, 102));
        HelperLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        HelperLabel.setForeground(new java.awt.Color(255, 255, 255));
        HelperLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HelperLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(HelperLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, 21));

        jTextArea1.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 380, 530));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 380, 570));

        jTabbedPane1.setForeground(new java.awt.Color(0, 133, 132));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        PingPanel.setBackground(new java.awt.Color(255, 255, 255));

        PingBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PingBoxMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                PingBoxMouseExited(evt);
            }
        });
        PingBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PingBoxActionPerformed(evt);
            }
        });

        PingBoton.setBackground(new java.awt.Color(0, 102, 102));
        PingBoton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PingBoton.setForeground(new java.awt.Color(255, 255, 255));
        PingBoton.setText("Hacer Ping");
        PingBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PingBotonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PingBotonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                PingBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PingPanelLayout = new javax.swing.GroupLayout(PingPanel);
        PingPanel.setLayout(PingPanelLayout);
        PingPanelLayout.setHorizontalGroup(
                PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PingPanelLayout.createSequentialGroup()
                                .addContainerGap(608, Short.MAX_VALUE)
                                .addGroup(PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                PingPanelLayout.createSequentialGroup()
                                                        .addComponent(PingBoton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(237, 237, 237))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                PingPanelLayout.createSequentialGroup()
                                                        .addComponent(PingBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(222, 222, 222)))));
        PingPanelLayout.setVerticalGroup(
                PingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PingPanelLayout.createSequentialGroup()
                                .addContainerGap(379, Short.MAX_VALUE)
                                .addComponent(PingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(PingBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)));

        jTabbedPane1.addTab("Ping", PingPanel);

        TracePanel.setBackground(new java.awt.Color(255, 255, 255));

        TraceBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBox1MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBox1MouseExited(evt);
            }
        });
        TraceBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraceBox1ActionPerformed(evt);
            }
        });

        TraceBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBox2MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBox2MouseExited(evt);
            }
        });

        TraceBoton.setBackground(new java.awt.Color(0, 102, 102));
        TraceBoton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TraceBoton.setForeground(new java.awt.Color(255, 255, 255));
        TraceBoton.setText("Trazar Ruta");
        TraceBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraceBotonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TraceBotonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                TraceBotonMouseExited(evt);
            }
        });
        TraceBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraceBotonActionPerformed(evt);
            }
        });

        DecorLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DecorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DecorLabel.setText(" < - - - - - ? ? ? - - - - - >");

        javax.swing.GroupLayout TracePanelLayout = new javax.swing.GroupLayout(TracePanel);
        TracePanel.setLayout(TracePanelLayout);
        TracePanelLayout.setHorizontalGroup(
                TracePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TracePanelLayout.createSequentialGroup()
                                .addGap(450, 450, 450)
                                .addComponent(TraceBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DecorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(TraceBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TracePanelLayout.createSequentialGroup()
                                .addGap(500, 500, 500)
                                .addComponent(TraceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        TracePanelLayout.setVerticalGroup(
                TracePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TracePanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(TracePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TraceBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 50,
                                                Short.MAX_VALUE)
                                        .addComponent(TraceBox1)
                                        .addComponent(DecorLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388,
                                        Short.MAX_VALUE)
                                .addComponent(TraceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)));

        jTabbedPane1.addTab("Traceroute", TracePanel);

        RangoPanel.setBackground(new java.awt.Color(255, 255, 255));

        RangoBox1.setEditable(true);
        RangoBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RangoBox1MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                RangoBox1MouseExited(evt);
            }
        });

        RangoBoton.setBackground(new java.awt.Color(0, 102, 102));
        RangoBoton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RangoBoton.setForeground(new java.awt.Color(255, 255, 255));
        RangoBoton.setText("Ver equipos");
        RangoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RangoBotonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RangoBotonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                RangoBotonMouseExited(evt);
            }
        });
        RangoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RangoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RangoPanelLayout = new javax.swing.GroupLayout(RangoPanel);
        RangoPanel.setLayout(RangoPanelLayout);
        RangoPanelLayout.setHorizontalGroup(
                RangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RangoPanelLayout.createSequentialGroup()
                                .addContainerGap(577, Short.MAX_VALUE)
                                .addComponent(RangoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(253, 253, 253))
                        .addGroup(RangoPanelLayout.createSequentialGroup()
                                .addGap(500, 500, 500)
                                .addComponent(RangoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        RangoPanelLayout.setVerticalGroup(
                RangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RangoPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(RangoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388,
                                        Short.MAX_VALUE)
                                .addComponent(RangoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)));

        jTabbedPane1.addTab("Rango", RangoPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 620));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar Equipos");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {
        // ABRIR PANEL PARA EDITAR EQUIPOS
        // ACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        EquipoList.main(null);
        
    }

    private void PingBotonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBotonMouseEntered
        PingBoton.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_PingBotonMouseEntered

    private void PingBotonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBotonMouseExited
        PingBoton.setBackground(new java.awt.Color(0, 102, 102));
    }// GEN-LAST:event_PingBotonMouseExited

    private void TraceBotonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBotonMouseEntered
        TraceBoton.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_TraceBotonMouseEntered

    private void TraceBotonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBotonMouseExited
        TraceBoton.setBackground(new java.awt.Color(0, 102, 102));
    }// GEN-LAST:event_TraceBotonMouseExited

    private void PingBotonMouseClicked(java.awt.event.MouseEvent evt) {

        String id = red.validarEquipo((String) PingBox.getSelectedItem());
        HelperLabel.setText("");
        if (id != null) {
            jTextArea1.setText("Equipo '" + id + "' " + (calculo.ping(id) ? "activo" : "inactivo"));
        } else {
            jTextArea1.setText("El equipo '" + (String) PingBox.getSelectedItem() + "' no se ha encontrado en la red");
        }

    }

    private void PingBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PingBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PingBoxActionPerformed

    private void TraceBotonMouseClicked(java.awt.event.MouseEvent evt) {
        String id1 = (String) TraceBox1.getSelectedItem();
        String id2 = (String) TraceBox2.getSelectedItem();
        List<String> resultado = null;
        String msj = "";

        if (id1 != null && id2 != null)
            resultado = calculo.traceRoute(id1, id2);
        if (resultado == null) {
            jTextArea1.setText("Al menos un equipo\n no se ha encontrado en la red");
            HelperLabel.setText(":c");
        } else if (resultado.isEmpty()) {
            jTextArea1.setText("No se ha encontrado un camino\n de equipos activos");
            HelperLabel.setText(":c");
        }
        // else if (!resultado.get(0).equals(id1) || !resultado.get(resultado.size() -
        // 1).equals(id2)){                                                      ESTE DA FALSO POSITIVO
        // jLabel1.setText("No se ha encontrado un camino de equipos activos");
        // jLabel2.setText(":c");}
        else {
            HelperLabel.setText("Camino encontrado:");
            for (int i = 0; i < resultado.size() - 1; i++) {

                id1 = resultado.get(i);
                id2 = resultado.get(i + 1);
                msj = msj + ("- " + id1 + " -> " + id2) + "\n";
            }
            jTextArea1.setText(msj);
        }
    }

    private void PingBoxMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBoxMouseEntered
        PingBox.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_PingBoxMouseEntered

    private void PingBoxMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PingBoxMouseExited
        PingBox.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_PingBoxMouseExited

    private void RangoBotonMouseClicked(java.awt.event.MouseEvent evt) {     
        List<String> equiposConEsaIP = red.rangoEquiposIP((String) RangoBox1.getSelectedItem());
        String msj = "";
        int count = 0;
        
        if (equiposConEsaIP.isEmpty()) {
            jTextArea1.setText("Ningun equipo encontrado");
            HelperLabel.setText("F");
        } else {
            Map<String, Boolean> resultado = calculo.rangoPing(equiposConEsaIP);
            HelperLabel.setText("Estado de los equipos:");
            for (Map.Entry<String, Boolean> entry : resultado.entrySet()) {
                String id = entry.getKey();
                boolean isActivo = entry.getValue();
                msj = msj + (id + " " + (isActivo ? "activo \n" : "inactivo \n"));
                count++;

            }
            jTextArea1.setText(msj);

        }
    }

    private void TraceBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TraceBox1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox1MouseEntered
        TraceBox1.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_TraceBox1MouseEntered

    private void TraceBox1MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox1MouseExited
        TraceBox1.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_TraceBox1MouseExited

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void TraceBox2MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox2MouseEntered
        TraceBox2.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_TraceBox2MouseEntered

    private void TraceBox2MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TraceBox2MouseExited
        TraceBox2.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_TraceBox2MouseExited

    private void RangoBotonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RangoBotonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_RangoBotonActionPerformed

    private void RangoBotonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBotonMouseExited
        RangoBoton.setBackground(new java.awt.Color(0, 102, 102));
    }// GEN-LAST:event_RangoBotonMouseExited

    private void RangoBotonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBotonMouseEntered
        RangoBoton.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_RangoBotonMouseEntered

    private void RangoBox1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBox1MouseEntered
        RangoBox1.setBackground(new java.awt.Color(0, 133, 132));
    }// GEN-LAST:event_RangoBox1MouseEntered

    private void RangoBox1MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RangoBox1MouseExited
        RangoBox1.setBackground(new java.awt.Color(225, 225, 225));
    }// GEN-LAST:event_RangoBox1MouseExited

    private void TraceBotonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        try {
            ConexionBD.getInstance().connectToDatabase();
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DecorLabel;
    private javax.swing.JLabel HelperLabel;
    private javax.swing.JButton PingBoton;
    private javax.swing.JComboBox<String> PingBox;
    private javax.swing.JPanel PingPanel;
    private javax.swing.JButton RangoBoton;
    private javax.swing.JComboBox<String> RangoBox1;
    private javax.swing.JPanel RangoPanel;
    private javax.swing.JButton TraceBoton;
    private javax.swing.JComboBox<String> TraceBox1;
    private javax.swing.JComboBox<String> TraceBox2;
    private javax.swing.JPanel TracePanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
